ebook_site/ebook/urls.py
from django.urls import path
from ebook import views

app_name = 'ebook'

urlpatterns = [
    path('', views.index, name='index'),
    path('ebooks/<int:category>/<int:subject_id>', views.ebooks, name='ebooks'),
    path('ebooks/<int:category>/ebook/<int:ebook_id>', views.ebook, name='ebook'),
    path('search', views.search, name='search'),
    path('subjects', views.subjects, name='subjects'),
    path('preview/<int:ebook_id>',views.preview, name='preview'),
    path('download/<int:ebook_id>',views.download, name='download'),
]

ebook_site/ebook_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ebook.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ebook_site/ebook/models.py
from django.utils import timezone
from django.db import models
from django.core.validators import FileExtensionValidator


class EBook(models.Model):
    title = models.CharField(max_length=100, blank=False)
    file = models.FileField(upload_to='pdfs', validators=[
                            FileExtensionValidator(['pdf'])])
    thumbnail = models.ImageField(default='default/pdf_default.png')
    date = models.DateField(default=timezone.now)
    description = models.TextField(blank=True)
    category = models.SmallIntegerField()

    authors = models.ManyToManyField(
        'Author', related_name="ebook", blank=True)
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def ebook_category(self):
        if self.category:
            return 'E-Book'
        else:
            return 'Note'

    ebook_category.short_description = 'catergory'


class Author(models.Model):
    name = models.CharField(max_length=80, unique=True)

    def __str__(self):
        return self.name


class Subject(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

ebook_site/ebook/views.py
from wsgiref.util import FileWrapper
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.http import FileResponse, Http404
from django.core.paginator import Paginator
from .models import EBook, Subject


def index(request):
    subjects = Subject.objects.all()[:6]

    context = {
        'subjects': subjects,
    }

    return render(request, 'ebook/index.html', context)


def ebooks(request, category, subject_id):
    subjects = Subject.objects.order_by('title')
    ebooks = EBook.objects.order_by('-date').filter(category=category)

    if subject_id != 0:
        ebooks = ebooks.filter(subject_id=subject_id)

    paginator = Paginator(ebooks, 6)
    page = request.GET.get('page')
    ebooks = paginator.get_page(page)

    context = {
        'subjects': subjects,
        'ebooks': ebooks,
        'category': category
    }

    return render(request, 'ebook/ebooks.html', context)


def ebook(request, category, ebook_id):
    subjects = Subject.objects.order_by('title')
    ebook = get_object_or_404(EBook, id=ebook_id)

    context = {
        'subjects': subjects,
        'ebook': ebook,
    }

    return render(request, 'ebook/ebook.html', context)


def search(request):
    ebooks = EBook.objects.order_by('-date')

    resultset = []

    if 'search' in request.GET:
        search_query = request.GET['search']

        if search_query:
            resultset = ebooks.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(authors__name__icontains=search_query)
            )

    paginator = Paginator(ebooks, 8)
    page = request.GET.get('page')
    ebooks = paginator.get_page(page)

    context = {
        'ebooks': resultset,
        'value': request.GET['search']
    }

    return render(request, 'ebook/search.html', context)


def subjects(request):
    subjects = Subject.objects.all()

    paginator = Paginator(subjects, 6)
    page = request.GET.get('page')
    subjects = paginator.get_page(page)

    context = {
        'subjects': subjects,
    }

    return render(request, 'ebook/subjects.html', context)


def preview(request, ebook_id):
    ebook = EBook.objects.get(id=ebook_id)

    try:
        response = FileResponse(ebook.file)
        response['Content-Disposition'] = f'inline; filename={ebook.title}.pdf'

        return response

    except FileNotFoundError:
        return Http404


def download(request, ebook_id):
    ebook = EBook.objects.get(id=ebook_id)

    try:
        response = FileResponse(ebook.file)
        response['Content-Disposition'] = f'attachment; filename={ebook.title}.pdf'
        return response

    except FileNotFoundError:
        return Http404

ebook_site/ebook/templates/ebook/ebook.html
{% extends 'base.html' %} 

{% block content %} 
  <div class="showcase-secondary">
    <h2 class="showcase-heading display-4">{{ ebook.title }}</h2>
    {% if ebook.authors.all %} 
      <h5 class="showcase-subheading">by   
          {% for author in ebook.authors.all %}
            {{ author.name }}
          {% endfor %}  
      </h5>
    {% endif %}
  </div>

  <section class="main">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'ebook:index' %}">Home</a></li>
          <li class="breadcrumb-item">
            <a href="{% url 'ebook:ebooks' ebook.category 0 %}">
                Browse 
                {% if ebook.category == 0 %} 
                  E-Books 
                {% else %}
                  Notes
                {% endif %}
            </a> 
          </li>
          <li class="breadcrumb-item active" aria-current="page">
            COA
          </li>
        </ol>
      </nav>

      <div class="row">
        <div class="col-lg-8 offset-lg-2 mt-3">

          <div class="ebook-showcase">
            <div class="row">
              <div class="col-md-6">
                <img
                  class="ebook-img-lg"
                  src="{{ ebook.thumbnail.url }}"
                  alt="{{ ebook.title }}"
                />
              </div>
              <div class="col-md-6">
                <div class="ebook-details">
                  <h2 class="ebook-title">
                      {{ ebook.title }}
                  </h2>
                  <h5 class="ebook-text-muted"> 
                    {% if ebook.authors.all %} 
                      {% for author in ebook.authors.all %}
                        {{ author.name }}
                      {% endfor %}
                    {% endif %}
                    {% if ebook.description %}
                      {{ ebook.description }}  
                    {% endif %}
                  </h5>  
                  <div class="info">
                    Uploaded: <span class="val">{{ ebook.date }}</span>
                  </div>
                  <div class="info">Size: <span class="val">{{ ebook.file.size }} MB</span></div>
                  <div class="info">Pages: <span class="val">206</span></div>

                  <a href="{% url 'ebook:preview' ebook.id %}" class="btn btn-primary">Open</a>
                  <a href="{% url 'ebook:download' ebook.id %}" class="btn btn-secondary">Download</a>
                </div>
              </div>
            </div>
          </div>
        </div>
  
      </div>
    </div>
  </section>
{% endblock %}

ebook_site/ebook/templates/ebook/ebooks.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 
  <div class="showcase-secondary">
    <h1 class="showcase-heading display-4">
      Browse 
      {% if category == 0 %} 
        E-Books 
      {% else %}
        Notes
      {% endif %}
    </h1>
  </div>

  <section class="main">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'ebook:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">
            Browse
            {% if category == 0 %} 
              E-Books 
            {% else %}
              Notes
            {% endif %}
          </li>
        </ol>
      </nav>

      <div class="row">
        <div class="col-lg-8 mt-3">
          
            <h1 class="uppercase">
              {% if category == 0 %} 
                E-Books 
              {% else %}
                Notes
              {% endif %}
            </h1>

          {% if ebooks %}
            {% for ebook in ebooks %}
          
              <div class="ebook-card mb-4">
                <a href="{% url 'ebook:ebook' ebook.category ebook.id %}""
                  ><img
                    src="{{ ebook.thumbnail.url }}"
                    class="ebook-img"
                    alt="{{ ebook.title }}"
                /></a>

                <div class="card-body">
                  <div class="heading">
                    <h4 class="title">
                      <a href="{% url 'ebook:ebook' ebook.category ebook.id %}"
                        >{{ ebook.title }}</a
                      >
                    </h4>
                    <div class="ebook-text-muted">
                      {% if ebook.authors.all %} 
                        {% for author in ebook.authors.all %}
                          {{ author.name }}
                        {% endfor %}
                      {% endif %}
                      {% if ebook.description %}
                        {{ ebook.description }}  
                      {% endif %}
                    </div>
      
                  </div>

                  <div class="ebook-info">
                    <span class="val">{{ ebook.date }}</span> /
                    <span class="val">{{ ebook.file.size }}</span> /
                    <span class="val">260 pages</span>
                  </div>
                </div>
              </div>

            {% endfor %}
          {% else %}
            <p>No E-Books Available.</p>
          {%endif%}
        
          {% if ebooks.has_other_pages %}

            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center">
      
                <!-- previous part -->
                {% if ebooks.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ ebooks.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                {% endif %}
            
                {% for i in ebooks.paginator.page_range %}
                  {% if ebooks.number == i %}
                    <li class="page-item active">
                      <a class="page-link" href="#">{{ i }}</a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
            
                <!-- next part -->
                {% if ebooks.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ ebooks.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
    
          {% endif %}

        </div>

        <div class="col-lg-4 mt-3">
          <h1 class="uppercase">Subjects</h1>

          <div class="card subject">

            <a id="subject0" href="{% url 'ebook:ebooks' category 0 %}" class="list-item">
              <i class="icon fas fa-book"></i> All
            </a>

            {% for subject in subjects %}
              <a id="subject{{ subject.id }}" href="{% url 'ebook:ebooks' category subject.id %}" class="list-item">
                <i class="icon fas fa-book"></i> {{ subject.title }}
              </a>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}

<script src="{% static 'ebook/js/color_toggler.js' %}">
</script>

{% endblock %}

ebook_site/ebook/templates/ebook/index.html
{% extends 'base.html' %} 

{% load static %}

{% block content %} 
  <div class="showcase">
    <h1 class="showcase-heading display-4">Welcome to EBook Store</h1>

    <div class="search-box">
      <form action="{% url 'ebook:search' %}" method="GET">
        <input name="search" class="search-field" type="input" placeholder="Search..." />
        <button class="search-btn" href="" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </form>
    </div>
  </div>

  <section class="main">
    <div class="container">
      <h1 class="main-heading uppercase mt-2 mb-4">Subjects</h1>

      <div class="row">

          {% for subject in subjects %}

            <div class="col-lg-4 col-md-6">
              <div class="sub-card">
                <div class="sub-head">
                  <img class="sub-img" src="{% static 'ebook/img/book-icon.svg' %}" alt="" />

                  <h4 class="sub-title">{{ subject.title }}</h4>
                </div>
                <a href="{% url 'ebook:ebooks' 0 subject.id %}" class="btn btn-primary btn-block"
                  >E-Book</a
                >
                <a href="{% url 'ebook:ebooks' 1 subject.id %}" class="btn btn-secondary btn-block"
                  >Notes</a
                >
              </div>
            </div>

          {% endfor %}
          
      </div>

      <div class="view-more">
        <a href="{% url 'ebook:subjects' %}" class="btn btn-primary px-4 py-2"
          >View all Subjects <i class="fas fa-arrow-right"></i
        ></a>
      </div>
    </div>
  </section>
{% endblock %}

ebook_site/ebook/templates/ebook/search.html
{% extends 'base.html' %} 

{% block content %}
<div class="showcase-secondary">
  <div class="search-box">
    <form action="{% url 'ebook:search' %}" method="GET">
      <input name="search" class="search-field" type="input" placeholder="Search..." value="{{ value }}" autofocus/>
      <button class="search-btn" href="" type="submit">
        <i class="fas fa-search"></i>
      </button>
    </form>
  </div>
</div>

  <section class="main">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'ebook:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">
            Search Results
          </li>
        </ol>
      </nav>

      <h1 class="main-heading uppercase mt-4 mb-4">Search Results</h1>

      {% if ebooks %}

        <div class="row">

          {% for ebook in ebooks %}

            <div class="col-lg-6">
              <div class="ebook-card mb-4">
                <a href="{% url 'ebook:ebook' ebook.category ebook.id %}""
                  ><img
                    src="{{ ebook.thumbnail.url }}"
                    class="ebook-img"
                    alt="{{ ebook.title }}"
                /></a>

                <div class="card-body">
                  <div class="heading">
                    <h4 class="title">
                      <a href="{% url 'ebook:ebook' ebook.category ebook.id %}"
                        >{{ ebook.title }}</a
                      >
                    </h4>
                    <div class="ebook-text-muted">
                      {% if ebook.authors.all %} 
                        {% for author in ebook.authors.all %}
                          {{ author.name }}
                        {% endfor %}
                      {% endif %}
                      {% if ebook.description %}
                        {{ ebook.description }}  
                      {% endif %}
                    </div>
      
                  </div>

                  <div class="ebook-info">
                    <span class="val">{{ ebook.date }}</span> /
                    <span class="val">{{ ebook.file.size }}</span> /
                    <span class="val">260 pages</span>
                  </div>
                </div>
              </div>

            </div>

          {% endfor %}

        </div>
        
      {% else %}
        <p>No E-Books Found.</p>
      {%endif%}

      {% if ebooks.has_other_pages %}

        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">

            <!-- previous part -->
            {% if ebooks.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ ebooks.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% endif %}
        
            {% for i in ebooks.paginator.page_range %}
              {% if ebooks.number == i %}
                <li class="page-item active">
                  <a class="page-link" href="#">{{ i }}</a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}
        
            <!-- next part -->
            {% if ebooks.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ ebooks.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>

      {% endif %}

    </div>
  </section>
{% endblock %}

ebook_site/ebook/templates/ebook/subjects.html
{% extends 'base.html' %} 

{% load static %}

{% block content %}
  <div class="showcase-secondary">
    <h1 class="showcase-heading display-4">Browse Subjects</h1>
  </div>

  <section class="main">
    <div class="container">

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'ebook:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">
            Subjects
          </li>
        </ol>
      </nav>

      <h1 class="main-heading uppercase mt-2 mb-4">Subjects</h1>

      <div class="row">

          {% for subject in subjects %}

            <div class="col-lg-4 col-md-6">
              <div class="sub-card">
                <div class="sub-head">
                  <img class="sub-img" src="{% static 'ebook/img/book-icon.svg' %}" alt="" />

                  <h4 class="sub-title">{{ subject.title }}</h4>
                </div>
                <a href="{% url 'ebook:ebooks' 0 subject.id %}" class="btn btn-primary btn-block">E-Book</a>
                <a href="{% url 'ebook:ebooks' 1 subject.id %}" class="btn btn-secondary btn-block">Notes</a>
              </div>
            </div>

          {% endfor %}
          
      </div>

      {% if subjects.has_other_pages %}

        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">

            <!-- previous part -->
            {% if subjects.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ subjects.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
            {% endif %}
        
            {% for i in subjects.paginator.page_range %}
              {% if subjects.number == i %}
                <li class="page-item active">
                  <a class="page-link" href="#">{{ i }}</a>
                </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                  </li>
              {% endif %}
            {% endfor %}
        
            <!-- next part -->
            {% if subjects.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ subjects.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>

      {% endif %}
        
    </div>
  </section>
{% endblock %}

ebook_site/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/all.min.css' %}"/>

    <!-- CSS Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'ebook/css/style.css' %}" />

    <title>E Book store</title>
  </head>
  <body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}
    
    <!-- Main content -->
    {% block content %} {% endblock %}

    <!-- Footer -->
    {% include 'partials/_footer.html' %}

    <!-- JQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Footer date -->
    <script src="{% static 'js/date.js' %}"></script>
    {% block script %} {% endblock %}
  </body>
</html>

ebook_site/templates/partials/_footer.html
<footer>
  Copyright &copy;
  <span class="year mx-1">2019</span> KC
</footer>

ebook_site/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container">
    <span class="navbar-brand mb-0 h1"><span class="main-brand">EBOOK</span>Store</span>

    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarContent"
      aria-controls="navbarContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav">
        <li class="nav-item {% if '/' == request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'ebook:index' %}">Home</a>
        </li>

        <li class="nav-item {% if 'ebooks/0' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'ebook:ebooks' 0 0 %}">Ebooks</a>
        </li>

        <li class="nav-item {% if 'ebooks/1' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'ebook:ebooks' 1 0 %}">Notes</a>
        </li>
      </ul>
    </div>
  </div>
</nav>